---
title: "Testing"
author: "Jan Moskal"
date: "2024-01-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(igraph)
library(tidyverse)
library(rvest)
```


```{r}
data <- read_csv("movies_actors_df.csv")

three_movies <- three_movies[1:54,]
movies_years <- data.frame(c("Skazani na Shawshank", "Mroczny Rycerz", "Ojciec chrzestny"),
                           c(1994, 2008, 1972))
colnames(movies_years) <- c("movie", "year")

three_movies <- left_join(three_movies, movies_years) 
```


```{r}
url <- "https://www.imdb.com/chart/top/?ref_=nv_mv_250"
page <- read_html(url)

movie <- page %>% html_nodes( "div.ipc-metadata-list-summary-item__c > div > div > div.ipc-title.ipc-title--base.ipc-title--title.ipc-title-link-no-icon.ipc-title--on-textPrimary.sc-935ed930-9.AguIe.cli-title > a > h3") %>% html_text()

year <- page %>% html_nodes("div.sc-935ed930-7.bHIxWH.cli-title-metadata > span:nth-child(1)") %>%  html_text()

ranking <- page %>%  html_nodes("div.ipc-metadata-list-summary-item__c > div > div > span > div > span") %>% html_text()

movies_data <- data.frame(movie, year, ranking)

test <- movies_data %>%
    mutate(votes = str_sub(ranking, 5),
           ranking = str_sub(ranking, 1, 3))

test$votes <- str_replace(test$votes, "K", "000")
test$votes <- str_replace(test$votes, "M", "000000")
test$votes <- str_remove_all(test$votes, "\\(|\\)")
test$votes <- as.numeric(test$votes)
test$votes <- if_else(str_detect(test$votes, "\\."), test$votes * 1000000, test$votes)
test$ranking <- as.numeric(test$ranking)
test$year <- as.integer(test$year)
test$movie <- str_remove(test$movie, "\\d+\\.+ ")



number_of_actors <- data %>% group_by(movie) %>% count()
data <- left_join(data, number_of_actors) 

final_data <- left_join(data, test)
row_index <- which(final_data$movie == "Tańczący z wilkami")
final_data[row_index, "votes"] <- 286000

final_data %>% 
  mutate(ranking = ranking / n,
         year = year / n,
         votes = votes / n) %>% 
  select(-n)

write_csv(final_data, "movies_actors_extended_df.csv")
saveRDS(final_data, "movies_actors_extended_df.rds")
```


