---
title: "MoviesNetworkGraphAnalysis"
output: html_document
date: "2023-12-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
# Libraries and functions
library(tidyverse)
library(igraph)
```

```{r, include=FALSE}
# Reading movies_actors_graph
movies_actors_graph <- read.graph("movies_actors_graph.graphml", format = "graphml")
```

## Analysis of the network as a whole
```{r}
# Graph basic parameters
V(movies_actors_graph)
vcount(movies_actors_graph) # 4079 vertexes(250 movies and 3829 actors)
E(movies_actors_graph)
ecount(movies_actors_graph) # 4433 edges

# Graph degree
dg_all <- degree(movies_actors_graph) # Distribution: mostly 1(actors) and 18(because most movies got 18 actors added) 
dg_out <- degree(movies_actors_graph, mode = "out") # Distribution: almost all 1 and some 18
dg_in <- degree(movies_actors_graph, mode = "in") # 0 degree - all movies, mostly 1 and 2  
mean(degree(movies_actors_graph)) 
# Around 2.17, mostly because a lot of actors play in one movie on the list of top 250 and movies have a lot of actors

max(dg_all) # 18
V(movies_actors_graph)$name[which(dg_all == max(dg_all))] # Most movies (240/250) have 18 actors
min(dg_all) # 1
V(movies_actors_graph)$name[which(dg_all == min(dg_all))] # Most actors play in one movie

max(dg_in) # 9
V(movies_actors_graph)$name[which(dg_in == max(dg_in))] # Robert De Niro played in the greatest number of movies on the list 
min(dg_in) # 0
V(movies_actors_graph)$name[which(dg_in == min(dg_in))] # All movies are here with 0 degree

max(dg_out) # 18
V(movies_actors_graph)$name[which(dg_out == max(dg_out))] # Movies with a lot of actors
min(dg_out) # 0
V(movies_actors_graph)$name[which(dg_out == min(dg_out))] # All actors are here with 0 degree


# Graph coherence
is.connected(movies_actors_graph, mode = "strong") 
# Not connected, because there are only edges out for movies vertexes, and edges in for actors vertexes
cds1 <- components(movies_actors_graph, mode = "strong")
is.connected(movies_actors_graph, mode = "weak") 
# Not connected, because there are only edges out for movies vertexes, and edges in for actors vertexes
cds2 <- components(movies_actors_graph, mode = "weak")

plot(movies_actors_graph, vertex.color = cds1$membership, edge.arrow.width = 0.01, vertex.label = NA)
plot(movies_actors_graph, vertex.color = cds2$membership, edge.arrow.width = 0.01, vertex.label = NA)


# Graph density
edge_density(movies_actors_graph) 
# A density of this magnitude suggests very few connections between movies and actors compared to all possible connections between them.
# This is related to fact that most actors are involved in a small number of movies from the list.
# Artistic Value and Quality: The Top 250 IMDb often includes movies of high artistic quality, where cast diversity might result from careful actor selection and their acting skills, contributing to the films' overall quality.
# International Character: Movies on this list may come from various countries and cultures, leading to actor diversity associated with different nationalities, languages, and acting styles.
# Directorial Creativity: The directors of these films might actively seek actor diversity, aiming to convey different perspectives and experiences through a variety of actors in their productions.


# Graph diameter
diameter(movies_actors_graph, directed = TRUE, unconnected = !is.connected(movies_actors_graph)) 
# The diameter is 1, because there is only one edge between two vertices (from movie to actor).
diameter(movies_actors_graph, directed = FALSE, unconnected = !is.connected(movies_actors_graph))
# A result of 20 could suggest that the longest path between the most distant vertices (movie-actor-movie-actor...)consists of 20 steps 

# Graph average path length
average.path.length(movies_actors_graph, directed = TRUE, unconnected = !is.connected(movies_actors_graph))  
# This suggests that in one of the connected components of the graph, the average distance between two vertices is 1 (from movie to actor).
average.path.length(movies_actors_graph, directed = FALSE, unconnected = !is.connected(movies_actors_graph))
# Such large average distances might arise due to various factors such as diverse movies, disjointed groups of movies or actors
```

## Analysis of individual vertex parameters 
```{r}
# Graph degree centrality
degree(movies_actors_graph) # Just like in the previous chunk
hist(degree(movies_actors_graph))
strength(movies_actors_graph) # Same as for degree
hist(strength(movies_actors_graph))


# Graph betweenness
bw1 <- betweenness(movies_actors_graph, directed = FALSE) 
summary(bw1)
# Most movies and actors lacks distinctly defined intermediary nodes, possibly due to an even distribution of connections between movies and actors. However, there are certain nodes that might play a slightly more significant role in connecting or bridging specific groups of movies or actors in the network.
max(bw1) #491269.2
V(movies_actors_graph)$name[which(bw1 == max(bw1))] # Lawrance of Arabia: Interesting phenomenon, worth checking or error

plot(movies_actors_graph, vertex.size = betweenness(movies_actors_graph, directed = FALSE) * 0.05, edge.arrow.width = 0.01, vertex.label = NA)

bw2 <- betweenness(movies_actors_graph) 
summary(bw2) # There is no betweenness for any vertex
max(bw2) # 0
V(movies_actors_graph)$name[which(bw2 == max(bw2))] # Every vertex is here

plot(movies_actors_graph, vertex.size = betweenness(movies_actors_graph, directed = FALSE) * 0.05, edge.arrow.width = 0.01, vertex.label = NA)

# Graph closeness
cl <- closeness(movies_actors_graph)

summary(cl)
max(cl) # Because graph is not connected there are some vertexes that are isolated from other ones
V(movies_actors_graph)$name[which(cl == 0.2)] # Persona: For max(cl) (but not NaN) worth checking
hist(closeness(movies_actors_graph))


# Graph eigen centrality
ec1 <- eigen_centrality(movies_actors_graph)
ec2 <- eigen_centrality(movies_actors_graph, directed = TRUE)

summary(ec1$vector)
max(ec1$vector) 
V(movies_actors_graph)$name[which(ec1$vector == 1)] # Gwiezdne wojny: Część V - Imperium kontratakuje: worth checking
summary(ec2$vector)
max(ec2$vector)
V(movies_actors_graph)$name[which(ec2$vector == max(ec2$vetor))] 

hist(ec1$vector)
hist(ec2$vector)
# Graph PageRank
pg1 <- page_rank(movies_actors_graph, directed = FALSE)
pg2 <- page_rank(movies_actors_graph)

max(pg1$vector)
V(movies_actors_graph)$name[which(pg1$vector == max(pg1$vector))] # Some movies, worth checking
min(pg1$vector)
V(movies_actors_graph)$name[which(pg1$vector == min(pg1$vector))] # Some actors, worth checking

max(pg2$vector)
V(movies_actors_graph)$name[which(pg2$vector == max(pg2$vector))] 
# Robert de Niro highest chances of landing while traversing the graph
min(pg2$vector)
V(movies_actors_graph)$name[which(pg2$vector == min(pg2$vector))] # All movies because graph is not connected

hist(pg1$vector)
hist(pg2$vector)
# Graph eccentricity
ecc <- eccentricity(movies_actors_graph)

summary(ecc)
max(ecc)
V(movies_actors_graph)$name[which(ecc == max(ecc))] # Some actors, worth checking
min(ecc)
V(movies_actors_graph)$name[which(ecc == min(ecc))] # Some movies, worth checking

hist(ecc)
```

## Cluster analysis
```{r}
movies_actors_undirected_df <- read_csv("movies_actors_df.csv")
movies_actors_undirected_graph <- graph.data.frame(movies_actors_undirected_df, directed = FALSE)


# Clustering - multilevel (louvain) algorithm
l <- cluster_louvain(movies_actors_undirected_graph)
length(l) # number of communities
sort(sizes(l)) # sorted by increasing community sizes
round(modularity(l), 6) # modularity rounded to 6 decimal places
membership(l) # which vertex belongs to which community
communities(l) # composition of individual communities


for (number in 1:length(l)) {
  V(movies_actors_undirected_graph)[membership(l) == number]$label
}
movies_actors_undirected_graph$community <- l$membership # atrybut społeczności
V(movies_actors_undirected_graph)$color <- movies_actors_undirected_graph$community # różne kolory dla różnych społeczności
movies_actors_undirected_graph$Modularity_Class <- l$membership
movies_actors_undirected_graph$Degree <- l$membership

comm1 <- induced_subgraph(movies_actors_undirected_graph, v = which(movies_actors_undirected_graph$community == 135))
# induced subgraph by the set of vertices from community 1
tkplot(comm1)



# Clustering - fast greedy algorithm
fg <- cluster_fast_greedy(movies_actors_undirected_graph)
length(fg) # number of communities
sort(sizes(fg)) # sorted by increasing community sizes
round(modularity(fg), 6) # modularity rounded to 6 decimal places
membership(fg) # which vertex belongs to which community
communities(fg) # composition of individual communities


for (number in 1:length(fg)) {
  V(movies_actors_undirected_graph)[membership(fg) == number]$label
}
movies_actors_undirected_graph$community <- l$membership # atrybut społeczności
V(movies_actors_undirected_graph)$color <- movies_actors_undirected_graph$community # różne kolory dla różnych społeczności
movies_actors_undirected_graph$Modularity_Class <- l$membership
movies_actors_undirected_graph$Degree <- l$membership

comm1 <- induced_subgraph(movies_actors_undirected_graph, v = which(movies_actors_undirected_graph$community == 1))
# induced subgraph by the set of vertices from community 1
tkplot(comm1)



# le <- cluster_leading_eigen(movies_actors_undirected_graph)
# eb <- cluster_edge_betweenness(movies_actors_undirected_graph)

## NMI
round(compare(l, fg, method = "nmi"), 6) # obliczenie parametru NMI podzialow (porównanie)
```
